version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - mongodb

  patient-service:
    build: ./services/patient-service
    container_name: patient-service
    ports:
      - "5002:5002"
    env_file:
      - ./services/patient-service/.env
    depends_on:
      - mongodb

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - patient-service

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - api-gateway

volumes:
  mongo_data: