apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: smart-healthcare-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:4001"
            - name: DOCTOR_SERVICE_URL
              value: "http://doctor-service:4002"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:4003"
            - name: PATIENT_SERVICE_URL
              value: "http://patient-service:4004"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:4005"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:4006"
