apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: smart-healthcare-notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4006
          env:
            - name: PORT
              value: "4006"
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              value: "sheronclerin1805@gmail.com"
            - name: SMTP_PASS
              value: "yyhq lycb omff ucrp"
            - name: EMAIL_FROM
              value: "CareLine@360.com"
            - name: SMSLENZ_USER_ID
              value: "1161"
            - name: SMSLENZ_API_KEY
              value: "764283fd-f3cb-49a0-b71c-b13c43a3361d"
            - name: SMSLENZ_SENDER_ID
              value: "SMSlenzDEMO"
