apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  selector:
    app: patient-service
  ports:
    - name: http
      protocol: TCP
      port: 4004
      targetPort: 4004
  type: ClusterIP
