apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: smart-healthcare-payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4005
          env:
            - name: PORT
              value: "4005"
            - name: MONGO_URI
              value: "mongodb+srv://thuverakantharma_db_user:1234ABC@careline360.jumdxls.mongodb.net/CareLine360"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:4003"
            - name: FRONTEND_URL
              value: "http://<YOUR_FRONTEND_PUBLIC_HOST>:5173"
            - name: STRIPE_CURRENCY
              value: "LKR"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STRIPE_WEBHOOK_SECRET
