services:
  auth-service:
    image: node:20-alpine
    container_name: auth-service
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm start"
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
      MONGO_URI: mongodb+srv://thuverakantharma_db_user:1234ABC@careline360.jumdxls.mongodb.net/CareLine360-DS
      JWT_SECRET: thuve
