services:
  doctor-service:
    image: node:20-alpine
    container_name: doctor-service
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm start"
    ports:
      - "4002:4002"
    environment:
      PORT: 4002
      MONGO_URI: mongodb+srv://thuverakantharma_db_user:1234ABC@careline360.jumdxls.mongodb.net/CareLine360
      JWT_SECRET: thuve
